language: python
python:
  - 3.6.4

addons:
  apt:
    update: true
    packages:
      - autoconf
      - libtool
      - nasm

install:
  - pip install -r requirements.txt
  - nvm install stable
  - npm install -g eslint-cli
  - npm install

script:
  - eslint --config .eslintrc.js bibliotekanarynku9_administration_panel/src/
  - npm run build
  - pylint --rcfile=.pylintrc bibliotekanarynku9_api/*

after_success:
  - coveralls
